import type { Api, Model } from "../src/types.js";

const fixtureModels = {
	"amazon-bedrock/eu.anthropic.claude-sonnet-4-5-20250929-v1:0": {
		id: "eu.anthropic.claude-sonnet-4-5-20250929-v1:0",
		name: "Claude Sonnet 4.5 (EU)",
		api: "bedrock-converse-stream",
		provider: "amazon-bedrock",
		baseUrl: "https://bedrock-runtime.eu-central-1.amazonaws.com",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 3.3,
			output: 16.5,
			cacheRead: 0.33,
			cacheWrite: 4.125,
		},
		contextWindow: 200000,
		maxTokens: 64000,
	},
	"amazon-bedrock/global.anthropic.claude-fable-5": {
		id: "global.anthropic.claude-fable-5",
		name: "Claude Fable 5 (Global)",
		api: "bedrock-converse-stream",
		provider: "amazon-bedrock",
		baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
		reasoning: true,
		thinkingLevelMap: { off: null, xhigh: "xhigh", max: "max" },
		input: ["text", "image"],
		cost: {
			input: 10,
			output: 50,
			cacheRead: 1,
			cacheWrite: 12.5,
		},
		contextWindow: 1000000,
		maxTokens: 128000,
	},
	"amazon-bedrock/global.anthropic.claude-opus-4-6-v1": {
		id: "global.anthropic.claude-opus-4-6-v1",
		name: "Claude Opus 4.6 (Global)",
		api: "bedrock-converse-stream",
		provider: "amazon-bedrock",
		baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
		reasoning: true,
		thinkingLevelMap: { max: "max" },
		input: ["text", "image"],
		cost: {
			input: 5,
			output: 25,
			cacheRead: 0.5,
			cacheWrite: 6.25,
		},
		contextWindow: 1000000,
		maxTokens: 128000,
	},
	"amazon-bedrock/global.anthropic.claude-opus-4-7": {
		id: "global.anthropic.claude-opus-4-7",
		name: "Claude Opus 4.7 (Global)",
		api: "bedrock-converse-stream",
		provider: "amazon-bedrock",
		baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
		reasoning: true,
		thinkingLevelMap: { xhigh: "xhigh", max: "max" },
		input: ["text", "image"],
		cost: {
			input: 5,
			output: 25,
			cacheRead: 0.5,
			cacheWrite: 6.25,
		},
		contextWindow: 1000000,
		maxTokens: 128000,
	},
	"amazon-bedrock/global.anthropic.claude-sonnet-4-5-20250929-v1:0": {
		id: "global.anthropic.claude-sonnet-4-5-20250929-v1:0",
		name: "Claude Sonnet 4.5 (Global)",
		api: "bedrock-converse-stream",
		provider: "amazon-bedrock",
		baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 3,
			output: 15,
			cacheRead: 0.3,
			cacheWrite: 3.75,
		},
		contextWindow: 200000,
		maxTokens: 64000,
	},
	"amazon-bedrock/us.anthropic.claude-opus-4-7": {
		id: "us.anthropic.claude-opus-4-7",
		name: "Claude Opus 4.7 (US)",
		api: "bedrock-converse-stream",
		provider: "amazon-bedrock",
		baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
		reasoning: true,
		thinkingLevelMap: { xhigh: "xhigh", max: "max" },
		input: ["text", "image"],
		cost: {
			input: 5,
			output: 25,
			cacheRead: 0.5,
			cacheWrite: 6.25,
		},
		contextWindow: 1000000,
		maxTokens: 128000,
	},
	"amazon-bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0": {
		id: "us.anthropic.claude-sonnet-4-5-20250929-v1:0",
		name: "Claude Sonnet 4.5 (US)",
		api: "bedrock-converse-stream",
		provider: "amazon-bedrock",
		baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 3,
			output: 15,
			cacheRead: 0.3,
			cacheWrite: 3.75,
		},
		contextWindow: 200000,
		maxTokens: 64000,
	},
	"anthropic/claude-haiku-4-5": {
		id: "claude-haiku-4-5",
		name: "Claude Haiku 4.5 (latest)",
		api: "anthropic-messages",
		provider: "anthropic",
		baseUrl: "https://api.anthropic.com",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 1,
			output: 5,
			cacheRead: 0.1,
			cacheWrite: 1.25,
		},
		contextWindow: 200000,
		maxTokens: 64000,
	},
	"anthropic/claude-opus-4-6": {
		id: "claude-opus-4-6",
		name: "Claude Opus 4.6",
		api: "anthropic-messages",
		provider: "anthropic",
		baseUrl: "https://api.anthropic.com",
		reasoning: true,
		thinkingLevelMap: { max: "max" },
		input: ["text", "image"],
		cost: {
			input: 5,
			output: 25,
			cacheRead: 0.5,
			cacheWrite: 6.25,
		},
		contextWindow: 1000000,
		maxTokens: 128000,
	},
	"anthropic/claude-opus-4-7": {
		id: "claude-opus-4-7",
		name: "Claude Opus 4.7",
		api: "anthropic-messages",
		provider: "anthropic",
		baseUrl: "https://api.anthropic.com",
		reasoning: true,
		thinkingLevelMap: { xhigh: "xhigh", max: "max" },
		input: ["text", "image"],
		cost: {
			input: 5,
			output: 25,
			cacheRead: 0.5,
			cacheWrite: 6.25,
		},
		contextWindow: 1000000,
		maxTokens: 128000,
	},
	"anthropic/claude-sonnet-4-5": {
		id: "claude-sonnet-4-5",
		name: "Claude Sonnet 4.5 (latest)",
		api: "anthropic-messages",
		provider: "anthropic",
		baseUrl: "https://api.anthropic.com",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 3,
			output: 15,
			cacheRead: 0.3,
			cacheWrite: 3.75,
		},
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	"anthropic/claude-sonnet-4-6": {
		id: "claude-sonnet-4-6",
		name: "Claude Sonnet 4.6",
		api: "anthropic-messages",
		provider: "anthropic",
		baseUrl: "https://api.anthropic.com",
		reasoning: true,
		thinkingLevelMap: { max: "max" },
		input: ["text", "image"],
		cost: {
			input: 3,
			output: 15,
			cacheRead: 0.3,
			cacheWrite: 3.75,
		},
		contextWindow: 1000000,
		maxTokens: 128000,
	},
	"azure-openai-responses/gpt-4o-mini": {
		id: "gpt-4o-mini",
		name: "GPT-4o mini",
		api: "azure-openai-responses",
		provider: "azure-openai-responses",
		baseUrl: "",
		reasoning: false,
		input: ["text", "image"],
		cost: {
			input: 0.15,
			output: 0.6,
			cacheRead: 0.075,
			cacheWrite: 0,
		},
		contextWindow: 128000,
		maxTokens: 16384,
	},
	"cerebras/gpt-oss-120b": {
		id: "gpt-oss-120b",
		name: "GPT OSS 120B",
		api: "openai-completions",
		provider: "cerebras",
		baseUrl: "https://api.cerebras.ai/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.35,
			output: 0.75,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 131072,
		maxTokens: 40960,
	},
	"cloudflare-ai-gateway/gpt-5.1": {
		id: "gpt-5.1",
		name: "GPT-5.1",
		api: "openai-responses",
		provider: "cloudflare-ai-gateway",
		baseUrl: "https://gateway.ai.cloudflare.com/v1/{CLOUDFLARE_ACCOUNT_ID}/{CLOUDFLARE_GATEWAY_ID}/openai",
		reasoning: true,
		thinkingLevelMap: { off: null },
		input: ["text", "image"],
		cost: {
			input: 1.25,
			output: 10,
			cacheRead: 0.125,
			cacheWrite: 0,
		},
		contextWindow: 128000,
		maxTokens: 128000,
	},
	"cloudflare-workers-ai/@cf/moonshotai/kimi-k2.6": {
		id: "@cf/moonshotai/kimi-k2.6",
		name: "Kimi K2.6",
		api: "openai-completions",
		provider: "cloudflare-workers-ai",
		baseUrl: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1",
		compat: { sendSessionAffinityHeaders: true },
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.95,
			output: 4,
			cacheRead: 0.16,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 256000,
	},
	"github-copilot/claude-haiku-4.5": {
		id: "claude-haiku-4.5",
		name: "Claude Haiku 4.5 (latest)",
		api: "anthropic-messages",
		provider: "github-copilot",
		baseUrl: "https://api.individual.githubcopilot.com",
		headers: {
			"User-Agent": "GitHubCopilotChat/0.48.1",
			"Editor-Version": "vscode/1.136.1",
			"Editor-Plugin-Version": "copilot-chat/0.48.1",
			"Copilot-Integration-Id": "vscode-chat",
		},
		compat: { supportsEagerToolInputStreaming: false },
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 1,
			output: 5,
			cacheRead: 0.1,
			cacheWrite: 1.25,
		},
		contextWindow: 200000,
		maxTokens: 64000,
	},
	"github-copilot/claude-sonnet-4.6": {
		id: "claude-sonnet-4.6",
		name: "Claude Sonnet 4.6",
		api: "anthropic-messages",
		provider: "github-copilot",
		baseUrl: "https://api.individual.githubcopilot.com",
		headers: {
			"User-Agent": "GitHubCopilotChat/0.48.1",
			"Editor-Version": "vscode/1.136.1",
			"Editor-Plugin-Version": "copilot-chat/0.48.1",
			"Copilot-Integration-Id": "vscode-chat",
		},
		reasoning: true,
		thinkingLevelMap: { max: "max" },
		input: ["text", "image"],
		cost: {
			input: 3,
			output: 15,
			cacheRead: 0.3,
			cacheWrite: 3.75,
		},
		contextWindow: 1000000,
		maxTokens: 32000,
	},
	"github-copilot/gpt-5.3-codex": {
		id: "gpt-5.3-codex",
		name: "GPT-5.3 Codex",
		api: "openai-responses",
		provider: "github-copilot",
		baseUrl: "https://api.individual.githubcopilot.com",
		headers: {
			"User-Agent": "GitHubCopilotChat/0.48.1",
			"Editor-Version": "vscode/1.136.1",
			"Editor-Plugin-Version": "copilot-chat/0.48.1",
			"Copilot-Integration-Id": "vscode-chat",
		},
		reasoning: true,
		thinkingLevelMap: { off: null, xhigh: "xhigh" },
		input: ["text", "image"],
		cost: {
			input: 1.75,
			output: 14,
			cacheRead: 0.175,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
	},

	"google-vertex/gemini-2.5-flash-lite": {
		id: "gemini-2.5-flash-lite",
		name: "Gemini 2.5 Flash Lite (Vertex)",
		api: "google-vertex",
		provider: "google-vertex",
		baseUrl: "https://{location}-aiplatform.googleapis.com",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.1,
			output: 0.4,
			cacheRead: 0.01,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 65536,
	},
	"google-vertex/gemini-2.5-flash-lite-preview": {
		id: "gemini-2.5-flash-lite-preview",
		name: "Gemini 2.5 Flash Lite Preview (Vertex)",
		api: "google-vertex",
		provider: "google-vertex",
		baseUrl: "https://{location}-aiplatform.googleapis.com",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.1,
			output: 0.4,
			cacheRead: 0.01,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 65536,
	},
	"google-vertex/gemini-3-flash-preview": {
		id: "gemini-3-flash-preview",
		name: "Gemini 3 Flash Preview (Vertex)",
		api: "google-vertex",
		provider: "google-vertex",
		baseUrl: "https://{location}-aiplatform.googleapis.com",
		reasoning: true,
		thinkingLevelMap: { off: null },
		input: ["text", "image"],
		cost: {
			input: 0.5,
			output: 3,
			cacheRead: 0.05,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 65536,
	},
	"groq/openai/gpt-oss-20b": {
		id: "openai/gpt-oss-20b",
		name: "GPT OSS 20B",
		api: "openai-completions",
		provider: "groq",
		baseUrl: "https://api.groq.com/openai/v1",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.075,
			output: 0.3,
			cacheRead: 0.0375,
			cacheWrite: 0,
		},
		contextWindow: 131072,
		maxTokens: 65536,
	},
	"huggingface/moonshotai/Kimi-K2.5": {
		id: "moonshotai/Kimi-K2.5",
		name: "Kimi-K2.5",
		api: "openai-completions",
		provider: "huggingface",
		baseUrl: "https://router.huggingface.co/v1",
		compat: { supportsDeveloperRole: false },
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.6,
			output: 3,
			cacheRead: 0.1,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 262144,
	},
	"mistral/devstral-medium-latest": {
		id: "devstral-medium-latest",
		name: "Devstral 2 (latest)",
		api: "mistral-conversations",
		provider: "mistral",
		baseUrl: "https://api.mistral.ai",
		reasoning: false,
		input: ["text"],
		cost: {
			input: 0.4,
			output: 2,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 262144,
	},
	"mistral/magistral-medium-latest": {
		id: "magistral-medium-latest",
		name: "Magistral Medium (latest)",
		api: "mistral-conversations",
		provider: "mistral",
		baseUrl: "https://api.mistral.ai",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 2,
			output: 5,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 128000,
		maxTokens: 16384,
	},
	"mistral/mistral-medium-3.5": {
		id: "mistral-medium-3.5",
		name: "Mistral Medium 3.5",
		api: "mistral-conversations",
		provider: "mistral",
		baseUrl: "https://api.mistral.ai",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 1.5,
			output: 7.5,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 262144,
		maxTokens: 262144,
	},
	"mistral/mistral-small-2603": {
		id: "mistral-small-2603",
		name: "Mistral Small 4",
		api: "mistral-conversations",
		provider: "mistral",
		baseUrl: "https://api.mistral.ai",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.15,
			output: 0.6,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 256000,
		maxTokens: 256000,
	},
	"mistral/pixtral-12b": {
		id: "pixtral-12b",
		name: "Pixtral 12B",
		api: "mistral-conversations",
		provider: "mistral",
		baseUrl: "https://api.mistral.ai",
		reasoning: false,
		input: ["text", "image"],
		cost: {
			input: 0.15,
			output: 0.15,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 128000,
		maxTokens: 128000,
	},

	"minimax/MiniMax-M2.7-highspeed": {
		id: "MiniMax-M2.7-highspeed",
		name: "MiniMax-M2.7-highspeed",
		api: "anthropic-messages",
		provider: "minimax",
		baseUrl: "https://api.minimax.io/anthropic",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.6,
			output: 2.4,
			cacheRead: 0.06,
			cacheWrite: 0.375,
		},
		contextWindow: 204800,
		maxTokens: 131072,
	},
	"openai/gpt-4o-mini": {
		id: "gpt-4o-mini",
		name: "GPT-4o mini",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: false,
		input: ["text", "image"],
		cost: {
			input: 0.15,
			output: 0.6,
			cacheRead: 0.075,
			cacheWrite: 0,
		},
		contextWindow: 128000,
		maxTokens: 16384,
	},
	"openai/gpt-5": {
		id: "gpt-5",
		name: "GPT-5",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: null },
		input: ["text", "image"],
		cost: {
			input: 1.25,
			output: 10,
			cacheRead: 0.125,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
	},
	"openai/gpt-5-mini": {
		id: "gpt-5-mini",
		name: "GPT-5 Mini",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: null },
		input: ["text", "image"],
		cost: {
			input: 0.25,
			output: 2,
			cacheRead: 0.025,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
	},
	"openai/gpt-5-nano": {
		id: "gpt-5-nano",
		name: "GPT-5 Nano",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: null },
		input: ["text", "image"],
		cost: {
			input: 0.05,
			output: 0.4,
			cacheRead: 0.005,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
	},
	"openai/gpt-5-pro": {
		id: "gpt-5-pro",
		name: "GPT-5 Pro",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: null },
		input: ["text", "image"],
		cost: {
			input: 15,
			output: 120,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 272000,
	},
	"openai/gpt-5.1": {
		id: "gpt-5.1",
		name: "GPT-5.1",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: "none" },
		input: ["text", "image"],
		cost: {
			input: 1.25,
			output: 10,
			cacheRead: 0.125,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
	},
	"openai/gpt-5.2": {
		id: "gpt-5.2",
		name: "GPT-5.2",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: "none", xhigh: "xhigh" },
		input: ["text", "image"],
		cost: {
			input: 1.75,
			output: 14,
			cacheRead: 0.175,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
	},
	"openai/gpt-5.2-pro": {
		id: "gpt-5.2-pro",
		name: "GPT-5.2 Pro",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: null, xhigh: "xhigh" },
		input: ["text", "image"],
		cost: {
			input: 21,
			output: 168,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
	},
	"openai/gpt-5.3-codex": {
		id: "gpt-5.3-codex",
		name: "GPT-5.3 Codex",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: "none", xhigh: "xhigh" },
		input: ["text", "image"],
		cost: {
			input: 1.75,
			output: 14,
			cacheRead: 0.175,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
	},
	"openai/gpt-5.4": {
		id: "gpt-5.4",
		name: "GPT-5.4",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: "none", xhigh: "xhigh" },
		input: ["text", "image"],
		cost: {
			input: 2.5,
			output: 15,
			cacheRead: 0.25,
			cacheWrite: 0,
		},
		contextWindow: 272000,
		maxTokens: 128000,
	},
	"openai/gpt-5.4-mini": {
		id: "gpt-5.4-mini",
		name: "GPT-5.4 mini",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: "none", xhigh: "xhigh" },
		input: ["text", "image"],
		cost: {
			input: 0.75,
			output: 4.5,
			cacheRead: 0.075,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
	},
	"openai/gpt-5.4-nano": {
		id: "gpt-5.4-nano",
		name: "GPT-5.4 nano",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: "none", xhigh: "xhigh" },
		input: ["text", "image"],
		cost: {
			input: 0.2,
			output: 1.25,
			cacheRead: 0.02,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
	},
	"openai/gpt-5.4-pro": {
		id: "gpt-5.4-pro",
		name: "GPT-5.4 Pro",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: null, xhigh: "xhigh" },
		input: ["text", "image"],
		cost: {
			input: 30,
			output: 180,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1050000,
		maxTokens: 128000,
	},
	"openai/gpt-5.5": {
		id: "gpt-5.5",
		name: "GPT-5.5",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: "none", xhigh: "xhigh" },
		input: ["text", "image"],
		cost: {
			input: 5,
			output: 30,
			cacheRead: 0.5,
			cacheWrite: 0,
		},
		contextWindow: 272000,
		maxTokens: 128000,
	},
	"openai/gpt-5.5-pro": {
		id: "gpt-5.5-pro",
		name: "GPT-5.5 Pro",
		api: "openai-responses",
		provider: "openai",
		baseUrl: "https://api.openai.com/v1",
		reasoning: true,
		thinkingLevelMap: { off: null, xhigh: "xhigh" },
		input: ["text", "image"],
		cost: {
			input: 30,
			output: 180,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1050000,
		maxTokens: 128000,
	},

	"openai-codex/gpt-5.3-codex": {
		id: "gpt-5.3-codex",
		name: "GPT-5.3 Codex",
		api: "openai-codex-responses",
		provider: "openai-codex",
		baseUrl: "https://chatgpt.com/backend-api",
		reasoning: true,
		thinkingLevelMap: { xhigh: "xhigh", minimal: "low" },
		input: ["text", "image"],
		cost: {
			input: 1.75,
			output: 14,
			cacheRead: 0.175,
			cacheWrite: 0,
		},
		contextWindow: 272000,
		maxTokens: 128000,
	},
	"openai-codex/gpt-5.4": {
		id: "gpt-5.4",
		name: "GPT-5.4",
		api: "openai-codex-responses",
		provider: "openai-codex",
		baseUrl: "https://chatgpt.com/backend-api",
		reasoning: true,
		thinkingLevelMap: { xhigh: "xhigh", minimal: "low" },
		input: ["text", "image"],
		cost: {
			input: 2.5,
			output: 15,
			cacheRead: 0.25,
			cacheWrite: 0,
		},
		contextWindow: 272000,
		maxTokens: 128000,
	},
	"openai-codex/gpt-5.5": {
		id: "gpt-5.5",
		name: "GPT-5.5",
		api: "openai-codex-responses",
		provider: "openai-codex",
		baseUrl: "https://chatgpt.com/backend-api",
		reasoning: true,
		thinkingLevelMap: { xhigh: "xhigh", minimal: "low" },
		input: ["text", "image"],
		cost: {
			input: 5,
			output: 30,
			cacheRead: 0.5,
			cacheWrite: 0,
		},
		contextWindow: 272000,
		maxTokens: 128000,
	},

	"openrouter/anthropic/claude-sonnet-4": {
		id: "anthropic/claude-sonnet-4",
		name: "Anthropic: Claude Sonnet 4",
		api: "openai-completions",
		provider: "openrouter",
		baseUrl: "https://openrouter.ai/api/v1",
		compat: { supportsReasoningEffort: false },
		reasoning: true,
		thinkingLevelMap: { minimal: null, low: null, medium: null, high: "high", xhigh: null, max: null },
		input: ["text", "image"],
		cost: {
			input: 3,
			output: 15,
			cacheRead: 0.3,
			cacheWrite: 3.75,
		},
		contextWindow: 1000000,
		maxTokens: 64000,
	},
	"openrouter/deepseek/deepseek-r1": {
		id: "deepseek/deepseek-r1",
		name: "DeepSeek: R1",
		api: "openai-completions",
		provider: "openrouter",
		baseUrl: "https://openrouter.ai/api/v1",
		compat: { supportsReasoningEffort: false },
		reasoning: true,
		thinkingLevelMap: { off: null, minimal: null, low: null, medium: null, high: "high", xhigh: null, max: null },
		input: ["text"],
		cost: {
			input: 0.7,
			output: 2.5,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 64000,
		maxTokens: 16000,
	},
	"openrouter/z-ai/glm-4.5v": {
		id: "z-ai/glm-4.5v",
		name: "Z.ai: GLM 4.5V",
		api: "openai-completions",
		provider: "openrouter",
		baseUrl: "https://openrouter.ai/api/v1",
		compat: { supportsReasoningEffort: false },
		reasoning: true,
		thinkingLevelMap: { minimal: null, low: null, medium: null, high: "high", xhigh: null, max: null },
		input: ["text", "image"],
		cost: {
			input: 0.6,
			output: 1.7999999999999998,
			cacheRead: 0.11,
			cacheWrite: 0,
		},
		contextWindow: 65536,
		maxTokens: 16384,
	},
	"vercel-ai-gateway/anthropic/claude-opus-4.5": {
		id: "anthropic/claude-opus-4.5",
		name: "Claude Opus 4.5",
		api: "anthropic-messages",
		provider: "vercel-ai-gateway",
		baseUrl: "https://ai-gateway.vercel.sh",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 5,
			output: 25,
			cacheRead: 0.5,
			cacheWrite: 6.25,
		},
		contextWindow: 200000,
		maxTokens: 64000,
	},
	"vercel-ai-gateway/google/gemini-2.5-flash": {
		id: "google/gemini-2.5-flash",
		name: "Gemini 2.5 Flash",
		api: "anthropic-messages",
		provider: "vercel-ai-gateway",
		baseUrl: "https://ai-gateway.vercel.sh",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 0.3,
			output: 2.5,
			cacheRead: 0.03,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 65536,
	},
	"vercel-ai-gateway/openai/gpt-5.1-codex-max": {
		id: "openai/gpt-5.1-codex-max",
		name: "GPT 5.1 Codex Max",
		api: "anthropic-messages",
		provider: "vercel-ai-gateway",
		baseUrl: "https://ai-gateway.vercel.sh",
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 1.25,
			output: 10,
			cacheRead: 0.125,
			cacheWrite: 0,
		},
		contextWindow: 400000,
		maxTokens: 128000,
	},
	"xai/grok-code-fast-1": {
		id: "grok-code-fast-1",
		name: "Grok Code Fast 1",
		api: "openai-completions",
		provider: "xai",
		baseUrl: "https://api.x.ai/v1",
		reasoning: false,
		input: ["text"],
		cost: {
			input: 0.2,
			output: 1.5,
			cacheRead: 0.02,
			cacheWrite: 0,
		},
		contextWindow: 32768,
		maxTokens: 8192,
	},
	"xiaomi/mimo-v2.5-pro": {
		id: "mimo-v2.5-pro",
		name: "MiMo-V2.5-Pro",
		api: "anthropic-messages",
		provider: "xiaomi",
		baseUrl: "https://api.xiaomimimo.com/anthropic",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.435,
			output: 0.87,
			cacheRead: 0.0036,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 131072,
	},
	"xiaomi-token-plan-ams/mimo-v2.5-pro": {
		id: "mimo-v2.5-pro",
		name: "MiMo-V2.5-Pro",
		api: "anthropic-messages",
		provider: "xiaomi-token-plan-ams",
		baseUrl: "https://token-plan-ams.xiaomimimo.com/anthropic",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.435,
			output: 0.87,
			cacheRead: 0.0036,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 131072,
	},
	"xiaomi-token-plan-cn/mimo-v2.5-pro": {
		id: "mimo-v2.5-pro",
		name: "MiMo-V2.5-Pro",
		api: "anthropic-messages",
		provider: "xiaomi-token-plan-cn",
		baseUrl: "https://token-plan-cn.xiaomimimo.com/anthropic",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.435,
			output: 0.87,
			cacheRead: 0.0036,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 131072,
	},
	"xiaomi-token-plan-sgp/mimo-v2.5-pro": {
		id: "mimo-v2.5-pro",
		name: "MiMo-V2.5-Pro",
		api: "anthropic-messages",
		provider: "xiaomi-token-plan-sgp",
		baseUrl: "https://token-plan-sgp.xiaomimimo.com/anthropic",
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0.435,
			output: 0.87,
			cacheRead: 0.0036,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 131072,
	},
	"zai/glm-5.3": {
		id: "glm-5.3",
		name: "GLM-5.3",
		api: "openai-completions",
		provider: "zai",
		baseUrl: "https://api.z.ai/api/coding/paas/v4",
		compat: { supportsDeveloperRole: false, thinkingFormat: "zai", zaiToolStream: true },
		reasoning: true,
		input: ["text"],
		cost: {
			input: 0,
			output: 0,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 1000000,
		maxTokens: 131072,
	},
	// Prime Inference fixtures carry the reasoning controls the client derives
	// from the live catalog's supported_parameters/reasoning metadata
	// (getPrimeInferenceReasoningControls applied over the bundled templates by
	// buildPrimeInferenceModels; the derivation is covered by the catalog
	// tests). Gateway-verified 2026-09-21: z-ai/glm-5.3 declares reasoning_effort
	// with efforts low/high/max and mandatory reasoning; z-ai/glm-4.7 declares
	// only the optional reasoning toggle (no effort selector).
	"prime-inference/z-ai/glm-5.3": {
		id: "z-ai/glm-5.3",
		name: "GLM 5.3",
		api: "openai-completions",
		provider: "prime-inference",
		baseUrl: "https://api.pinference.ai/api/v1",
		compat: {
			supportsStore: false,
			supportsDeveloperRole: false,
			supportsReasoningEffort: true,
			maxTokensField: "max_tokens",
			supportsStrictMode: false,
		},
		reasoning: true,
		thinkingLevelMap: { off: null, minimal: null, low: "low", medium: null, high: "high", xhigh: null, max: "max" },
		input: ["text"],
		cost: {
			input: 1.4,
			output: 4.4,
			cacheRead: 0.26,
			cacheWrite: 1.4,
		},
		contextWindow: 1048576,
		maxTokens: 131072,
	},
	"prime-inference/z-ai/glm-4.7": {
		id: "z-ai/glm-4.7",
		name: "GLM 4.7",
		api: "openai-completions",
		provider: "prime-inference",
		baseUrl: "https://api.pinference.ai/api/v1",
		compat: {
			supportsStore: false,
			supportsDeveloperRole: false,
			supportsReasoningEffort: false,
			maxTokensField: "max_tokens",
			supportsStrictMode: false,
			thinkingFormat: "openrouter",
		},
		reasoning: true,
		thinkingLevelMap: { minimal: null, low: null, medium: null, high: "high", xhigh: null, max: null },
		input: ["text"],
		cost: {
			input: 0.6,
			output: 2.2,
			cacheRead: 0,
			cacheWrite: 0,
		},
		contextWindow: 204800,
		maxTokens: 131072,
	},
	"cloudflare-ai-gateway/claude-sonnet-4.6": {
		id: "claude-sonnet-4.6",
		name: "Claude Sonnet 4.6",
		api: "anthropic-messages",
		provider: "cloudflare-ai-gateway",
		baseUrl: "https://gateway.ai.cloudflare.com/v1/{CLOUDFLARE_ACCOUNT_ID}/{CLOUDFLARE_GATEWAY_ID}/anthropic",
		reasoning: true,
		thinkingLevelMap: { max: "max" },
		input: ["text", "image"],
		cost: {
			input: 3,
			output: 15,
			cacheRead: 0.3,
			cacheWrite: 3.75,
		},
		contextWindow: 1000000,
		maxTokens: 128000,
	},
} satisfies Record<string, Model<Api>>;

export function getFixtureModel<TApi extends Api = Api>(provider: string, modelId: string): Model<TApi> {
	const model = fixtureModels[`${provider}/${modelId}` as keyof typeof fixtureModels];
	if (!model) throw new Error(`Missing fixture model: ${provider}/${modelId}`);
	return model as Model<TApi>;
}
